app: serverless-example
service: aws-cli-layer

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  stage: prod
  region: eu-central-1

package:
  individually: true

layers:
  ${file(missed-split/aws-cli-layer/awsCliLayer.yml)}
        