Resources:
  CheckPITRStatusRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Statement: 
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies: 
        - PolicyName: root
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 
                  - dynamodb:DescribeTable
                Resource: 
                  - ARN+TB1
                  - ARN_TB2
      RoleName: ${self:app}-${self:provider.stage}-check-PITR-status-role
      Tags:
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Name
          Value: ${self:app}-${self:provider.stage}-check-PITR-status-role
        - Key: Product
          Value: ${self:app}  